framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    php_errors:
        log: true
    
    serializer:
        enable_annotations: true
        mapping:
            paths: ['%kernel.project_dir%/config/serialization']
    
    validation:
        email_validation_mode: html5 