api_login_check:
    path: /api/login_check

api_posts:
    resource: '../src/Controller/PostController.php'
    type: attribute
    prefix: /api

api_users:
    resource: '../src/Controller/UserController.php'
    type: attribute
    prefix: /api 